apiVersion: v1
kind: Service
metadata:
  name: inventory
spec:
  selector:
    app: inventory

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
spec:
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      securityContext:
        runAsUser: 10000
        runAsGroup: 10000
        fsGroup: 10000
      terminationGracePeriodSeconds: 60
      containers:
      - name: inventory
        image: inventory-image
        resources:
          requests:
            cpu: "250m"
            memory: "36Mi"
          limits:
            cpu: "250m"
            memory: "36Mi"
        ports:
        - name: inventory
          containerPort: 8080
        - name: inventory-debug
          containerPort: 8081        
        envFrom:
          - secretRef:
              name: postgres-creds      
        env:
        - name: GOMAXPROCS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
        - name: GOMEMLIMIT
          valueFrom:
            resourceFieldRef:
              resource: limits.memory
        - name: KEYS_DIR
          value: /etc/keys
        volumeMounts:
          - name: keys-volume
            mountPath: /etc/keys
            readOnly: true
        readinessProbe:
          httpGet:
            path: /v1/readiness
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 2
        livenessProbe:
          httpGet:
            path: /v1/liveness
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 2
      volumes:
        - name: keys-volume
          secret:
            secretName: jwt-keys
            defaultMode: 0440
