apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bookshelf-system
resources:
- grafana.yaml
images:
- name: grafana
  newName: grafana/grafana
  newTag: 12.0.0
- name: grafana-image
  newName: grafana/grafana
  newTag: 12.0.0
