apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bookshelf-system
resources:
- loki.yaml
images:
- name: loki
  newName: grafana/loki
  newTag: 3.5.0
- name: loki-image
  newName: grafana/loki
  newTag: 3.5.0
