apiVersion: v1
kind: ConfigMap
metadata:
  name: pghbaconf
data:
  pg_hba.conf: |
    local   all             all                                     trust
    # IPv4 local connections:
    host    all             all             0.0.0.0/0               md5
    # IPv6 local connections:
    host    all             all             ::1/128                 md5
    # Allow replication connections from localhost, by a user with the
    # replication privilege.
    local   replication     all                                     trust
    host    replication     all             0.0.0.0/0               md5
    host    replication     all             ::1/128                 md5

---

apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  type: NodePort
  selector:
    app: database
  ports:
  - name: postgres
    port: 5432
    targetPort: postgres
    nodePort: 15432

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
spec:
  selector:
    matchLabels:
      app: database
  serviceName: database
  replicas: 1
  template:
    metadata:
      labels:
        app: database
    spec:
      securityContext:
        fsGroup: 999
      terminationGracePeriodSeconds: 60
      containers:
      - name: postgres
        image: postgres-image
        args: ['-c', 'hba_file=/etc/postgresql/pg_hba.conf']
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        ports:
        - name: postgres
          containerPort: 5432
        envFrom:
          - secretRef:
              name: postgres-creds
              optional: false
        volumeMounts:
          - name: data
            mountPath: /var/lib/postgresql/data
          - name: config
            mountPath: "/etc/postgresql/pg_hba.conf"
            subPath: "pg_hba.conf"
            readOnly: true        
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - pg_isready -h 127.0.0.1 -U "$POSTGRES_USER" -d "$POSTGRES_DB"
          initialDelaySeconds: 5
          timeoutSeconds: 3
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - pg_isready -h 127.0.0.1 -U "$POSTGRES_USER" -d "$POSTGRES_DB"
          initialDelaySeconds: 30
          timeoutSeconds: 5
      volumes:
        - name: config
          configMap:
            name: pghbaconf
            items:
              - key: "pg_hba.conf"
                path: "pg_hba.conf"
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: "standard"
      resources:
        requests:
          storage: 3Gi
