apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bookshelf-system
resources:
- ./database.yaml
images:
- name: postgres
  newName: postgres
  newTag: "17.4"
- name: postgres-image
  newName: postgres
  newTag: "17.4"
