apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bookshelf-system
resources:
- ../../base/inventory/
patches:
- path: ./inventory-patch.yaml
images:
- name: inventory-image
  newName: localhost/loobyte/inventory
  newTag: v0.1.0
